[package]
name = "rust-url-shortener"
version = "0.1.0"
edition = "2021"
authors = ["Srdjan Tubin <stubin87@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
