[package]
name = "rust-url-shortener"
version = "0.1.0"
edition = "2021"
authors = ["Srdjan Tubin <stubin87@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ctrlc = "3.2.2"
http = "0.2.7"
url = "2.2.2"
rand = "0.8.5"
