name: Deploy new Releasae

on:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  deployment:
    runs-on: ubuntu-20.04
    environment: production
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Build
        run: |
          echo "build starting ..."
          cargo build --all --release

      - name: Run pre-deploy script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.MISC_SERVER_HOST }}
          username: ${{ secrets.MISC_SERVER_SSH_USERNAME }}
          password: ${{ secrets.MISC_SERVER_SSH_PASSWORD }}
          port: ${{ secrets.MISC_SERVER_SSH_PORT }}
          script: ~/rust-url-shortener/pre-deploy.sh

      - name: Deploy [copy the app via ssh]
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.MISC_SERVER_HOST }}
          username: ${{ secrets.MISC_SERVER_SSH_USERNAME }}
          password: ${{ secrets.MISC_SERVER_SSH_PASSWORD }}
          port: ${{ secrets.MISC_SERVER_SSH_PORT }}
          source: "./target/release/rust-url-shortener"
          target: "/home/${{ secrets.MISC_SERVER_SSH_USERNAME }}/rust-url-shortener"

      - name: Run post-deploy script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.MISC_SERVER_HOST }}
          username: ${{ secrets.MISC_SERVER_SSH_USERNAME }}
          password: ${{ secrets.MISC_SERVER_SSH_PASSWORD }}
          port: ${{ secrets.MISC_SERVER_SSH_PORT }}
          script: ~/rust-url-shortener/post-deploy.sh
